export const TOOL_PATHS = {
  "documents": "/gerar-documentos",
  "qrcode": "/gerar-qrcode",
  "password": "/gerar-senha",
  "whatsapp": "/link-whatsapp",
  "person": "/gerar-pessoa",
  "hash": "/gerar-hash",
  "guid": "/guid-generator",
  "lorem": "/lorem-ipsum",
  "json": "/formatar-json",
  "xml": "/formatar-xml",
  "sql": "/formatar-sql",
  "json-class": "/conversor-json-class",
  "xml-json": "/conversor-xml-json",
  "json-stringify": "/json-stringify",
  "base64-file": "/conversor-base64-arquivo",
  "timestamp": "/timestamp-converter",
  "color": "/conversor-cores",
  "url": "/url-encode-decode",
  "base64": "/base64-encode-decode",
  "jwt": "/jwt-encode-decode",
  "ip": "/meu-ip",
  "html": "/visualizar-html",
  "overtime": "/calculo-hora-extra",
  "string-utils": "/string-utilities",
  "csv-json": "/conversor-csv-json",
  "json-yaml": "/conversor-json-yaml",
  "regex": "/testador-regex",
  "diff": "/comparar-textos",
  "numbase": "/conversor-base-numerica",
  "cron": "/explicador-cron",
  "markdown": "/preview-markdown",
};

/** Páginas estáticas (não-ferramentas) — entram no prerender e no sitemap. */
export const PAGE_PATHS = {
  privacy: "/politica-de-privacidade",
};
