export const TOOL_PATHS = {
  "documents": "/gerar-documentos",
  "qrcode": "/gerar-qrcode",
  "password": "/gerar-senha",
  "whatsapp": "/link-whatsapp",
  "person": "/gerar-pessoa",
  "hash": "/gerar-hash",
  "guid": "/guid-generator",
  "lorem": "/lorem-ipsum",
  "json": "/formatar-json",
  "xml": "/formatar-xml",
  "sql": "/formatar-sql",
  "json-class": "/conversor-json-class",
  "json-stringify": "/json-stringify",
  "base64-file": "/conversor-base64-arquivo",
  "timestamp": "/timestamp-converter",
  "color": "/conversor-cores",
  "url": "/url-encode-decode",
  "base64": "/base64-encode-decode",
  "jwt": "/jwt-encode-decode",
  "ip": "/meu-ip",
  "html": "/visualizar-html",
  "overtime": "/calculo-hora-extra",
  "string-utils": "/string-utilities",
};
